# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-18 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_fulldbresult', '0005_scheduling'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='taskresultmeta',
            index_together=set([('status', 'date_done')]),
        ),
    ]
