# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-19 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_fulldbresult', '0006_auto_20170718_2053'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='taskresultmeta',
            index_together=set([('status', 'date_done'), ('task', 'date_done')]),
        ),
    ]
